Repository bambinos/bambi, pull requests merged in 2023-10, with the labels that each got.

#731 Bug fix for plotting order in plot_comparison (fixes mismatch between labels and plot)
  bambi/backend/terms.py
  bambi/interpret/create_data.py
  bambi/interpret/plot_types.py
  bambi/interpret/plotting.py
  bambi/interpret/utils.py
Labels: bug

#732 `interpret` support for model predictions with response levels
  bambi/interpret/effects.py
  bambi/interpret/plot_types.py
  bambi/interpret/utils.py
  docs/notebooks/categorical_regression.ipynb
  tests/test_plots.py
Labels: bug, enhancement

#736 interpret predictions enhancements
  bambi/interpret/create_data.py
  bambi/interpret/effects.py
  bambi/interpret/plotting.py
  bambi/interpret/utils.py
  docs/notebooks/mister_p.ipynb
  docs/notebooks/plot_predictions.ipynb
  docs/notebooks/zero_inflated_regression.ipynb
  tests/test_plots.py
Labels: enhancement
